---
  name: 'Test PR'
  on:
    pull_request:
      branches:
        - "master"     
  
  # Stop in progress workflows on the same branch and same workflow to use latest committed code
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
  jobs:
    new-version-test:
      name: 'Test Proofs'
      runs-on: [self-hosted, linux, kaas]
      steps:
        - name: 'Check out code'
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.JENKINS_GITHUB_PAT }}
            fetch-depth: 0

        - name: "Install KaaS"
          uses: runtimeverification/install-kaas@v0.2.1
          with:
            github-token: ${{ secrets.JENKINS_GITHUB_PAT }}        
            
        - name: 'Get Kontrol Version'
          run: |
            set -euo pipefail
            # Get the version of the tool from the Dockerfile
            echo "kontrol-version=$(cat deps/kontrol_release)" >> $GITHUB_ENV
            # Get Repository Base name
            echo "repository_basename=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        
        - name: "Download KCFG Cache"
          shell: bash
          run: |
            pushd ./ > /dev/null
            kaas-cli download --token ${{ secrets.TEST_TOKEN }} runtimeverification/audit-kontrol-template:latest -d ./out/

        - name: Docker Login w/ Github Token
          uses: docker/login-action@v3.1.0
          with:
            username: rvdockerhub
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
        - name: 'Run Kontrol'
          run: |
            # Run the following in the running docker container
            ./test/kontrol/scripts/run-kontrol.sh script

        - name: 'KCFG KaaS Cache Upload'
          shell: bash
          run: |
            # Enter directory where `out` folder is generated, generally foundry.toml folder by default
            pushd ./ > /dev/null
            kaas-cli upload --token ${{ secrets.TEST_TOKEN }} runtimeverification/audit-kontrol-template:latest -d ./out/
            kaas-cli upload --token ${{ secrets.TEST_TOKEN }} runtimeverification/audit-kontrol-template:${{ github.ref_name }} -d ./out/
      
        - name: 'Upload KCFG results.tar.gz to GH Summary'
          if: always()
          uses: actions/upload-artifact@v4.3.1
          with:
            name: Kontrol Results
            path: ./**/results-*.tar.gz
            retention-days: 5
  
