---
name: "Update Kontrol Version"
on:
  push:
    branches:
      - "_update-deps/runtimeverification/kontrol"
jobs:
  update-version:
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Kontrol Version
        run: |
          echo "Update the version.json on Rev of Kontrol"
          KONTROL_VERSION=$(cat deps/kontrol_release)
          echo "Kontrol version: $KONTROL_VERSION"
          sed -i "s/\"kontrol\": \".*\"/\"kontrol\": \"$KONTROL_VERSION\"/g" versions.json
